### ISSUE TITLE
Missing highlights

### ISSUE THREAD

**Issue by DrKGD** [cathaysia/tree-sitter-loongdoc#7]
I had some trouble configuring the highlights as it does not install them (highlights.scm is missing); this is not really a _github_ issue, but here's my solution. 

My understanding of it is that [nvim-tree](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries) should have a copy of `highlights.scm` in the queries folder, which is not yet the case.

As suggested [on this very repository](https://github.com/cathaysia/tree-sitter-loongdoc?tab=readme-ov-file#usage), I installed both but I selected the _possibly trademarked name_ as the filetype, thus keeping the original asciidoctor `ftplugin` as fallback.
```lua
loongdoc = {
	install_info = {
		url = 'https://github.com/cathaysia/tree-sitter-loongdoc.git',
		files 	= { 'tree-sitter-loongdoc/src/parser.c', 'tree-sitter-loongdoc/src/scanner.c' },
		branch	= 'master',
		generate_requires_npm = false,
		requires_generate_from_grammar = false,
	},
	filetype = 'asciidoc',
},

loongdoc_inline = {
	install_info = {
		url = 'https://github.com/cathaysia/tree-sitter-loongdoc.git',
		files = { 'tree-sitter-loongdoc_inline/src/parser.c', 'tree-sitter-loongdoc_inline/src/scanner.c' },
		branch = 'master',
		generate_requires_npm = false,
		requires_generate_from_grammar = false,
	},
	filetype = 'asciidoc_inline',
}
```

Thus I cloned this repository as a standalone plugin, as a nvim-treesitter dependency (using `lazy`).

As treesitter only automatically accepts `queries/{language}/{highlights.scm}` and such as reported [here](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-queries), I symlink'd the respective queries directories to `$HOME/.local/share/nvim/rtp/queries/{lang}`, thus I added the path to the nvim runtimepath.

```lua
{ 'cathaysia/tree-sitter-loongdoc',
		name = 'treesitter.parser.loongdoc',
		init = function(spec)
			local rtp = ('%s/rtp'):format(vim.fn.stdpath('data'))
			vim.fn.mkdir(rtp, 'p')
			vim.opt.runtimepath:prepend(rtp)

			local queries = ('%s/queries'):format(rtp)
			vim.fn.mkdir(queries, 'p')

			-- Symlink queries folder for language
			vim.iter({ { 'tree-sitter-loongdoc', 'loongdoc' }, { 'tree-sitter-loongdoc_inline', 'loongdoc_inline' } })
				:each(function(tuple)
					local src = ('%s/%s/queries'):format(spec.dir, tuple[1])
					local dst = ('%s/%s'):format(queries, tuple[2])

					-- Path exists, either it is the wrong one, or it is fine as it is
					if vim.uv.fs_stat(dst) then
						assert(vim.uv.fs_readlink(dst) == src, ('%s link does not match the right source %q'):format(tuple[1], src))
						return end

					-- Symbolic link
					vim.uv.fs_symlink(src, dst, { dir = true })
				end)
		end },

```

Also, I tried using this local clone to automatically build the parsers on startup with `ensure_installed` (install_info also accepts a local url), but as `loongdoc` and `loongdoc_inline` shares the same working directory, they conflict with each other during the _build phase_.

One last thing, thanks a lot for your work and for the parser of course!

**Comment by cathaysia** [comment]
If you mean that after you installed queries, it still doesn't highlight. You can try using `TSToggle highlight` twice. This is because when nvim-treesitter is loaded, it determines whether highlighting is supported based on the file name.

If you don't want to run `TSToggle highlight` manually, you will need to change asciidoc to loongdoc.

**Comment by DrKGD** [comment]
Mh, I was more reporting the steps to use the _plugin_ as of right now which works for me and also asking if there was a better way to install highlights, I suppose there really isn't :laughing: 

It does indeed work and pretty well too!

**Comment by cathaysia** [comment]
Yes. I don't have any better ideas. :(

**Comment by cathaysia** [comment]
Is this what you want?

**Comment by DrKGD** [comment]
Yes, tysm!
